accounts/urls.py
# coding=utf-8

from django.conf.urls import url
from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^cadastro/$', views.register, name="register"),
    url(r'^alterar-dados/$', views.update_user, name="update_user"),
    url(r'^alterar-senha/$', views.update_password, name='update_password'),
]

checkout/urls.py
# coding=utf-8

from django.conf.urls import url
from django.core.exceptions import ImproperlyConfigured
from . import views

app_name = 'compras'
urlpatterns = [
    url(r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cart_item, name="create_cart_item"),
 	url(r'^carrinho/$', views.cart_item, name='cart_item'),
 	url(r'^finalizacao/$', views.checkout, name='checkout'),
	url(
        r'^finalizando/(?P<pk>\d+)/pagseguro/$', views.pagseguro_view,
        name='pagseguro_view'
	),
	url(
        r'^notificacoes/pagseguro/$', views.pagseguro_notification,
        name='pagseguro_notification'
    ),
 	url(r'^meus_pedidos/$', views.order_list, name='order_list'),		
 	url(r'^detalhes_do_pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from core import views
from catalogo import views as views_catalogo
from checkout import views as views_checkout

from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^catalogo/', include('catalogo.urls', namespace='catalogo')),
    url(r'^contato/$', views.contato, name="contato"),
    url(r'^compras/', include('checkout.urls', namespace="checkout")),
    url(r'^pesquisa/', include('pesquisa.urls', namespace="pesquisa")),
    url(r'^entrar/$', login, {'template_name':'login.html'}, name="login"),
    url(r'^sair/$', logout, {'next_page':'index'}, name="logout"),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),

]

accounts/models.py
# coding=utf-8

import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    name = models.CharField('Nome', max_length=100, blank=True)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

accounts/forms.py
# coding=utf-8

from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import User


class UserAdminCreationForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username','email']

class UserAdminForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ['username', 'email', 'name', 'is_active', 'is_staff']

accounts/views.py
# coding=utf-8

from django.shortcuts import render
from django.views.generic import (
    CreateView, TemplateView, UpdateView, FormView
)
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm

from .models import User
from .forms import UserAdminCreationForm


class IndexView(LoginRequiredMixin, TemplateView):

    template_name = 'accounts/index.html'


class RegisterView(CreateView):

    model = User
    template_name = 'accounts/registration.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')


class UpdateUserView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = 'accounts/update_user.html'
    fields = ['name', 'email']
    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user

class UpdatePasswordView(LoginRequiredMixin, FormView):
	template_name = 'accounts/update_password.html'
	success_url = reverse_lazy('accounts:index')
	form_class = PasswordChangeForm

	def get_form_kwargs(self):
		kwargs = super(UpdatePasswordView, self).get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs

index = IndexView.as_view()
register = RegisterView.as_view()
update_user = UpdateUserView.as_view()
update_password = UpdatePasswordView.as_view()

accounts/templates/accounts/index.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block title %}
    Minha conta | {{ block.super }}
{% endblock title %}

{% block container %}
 <div class="container margin-top">
        <div class="row">
            <div class="col-md-8">
                <div class="page-header">
    <div class="container margin-top">
        <ol class="breadcrumb">
          <li><a href="#">Início</a></li>
          <li class="active">Minha Conta</li>
        </ol>
        <div class="row">
            <div class="col-md-4">
                <div class="list-group">
                  <a href="{% url 'accounts:index' %}" class="list-group-item active">Minha Conta</a>
                  <a href="{% url 'accounts:update_user' %}" class="list-group-item">Alterar Dados</a>
                  <a href="{% url 'accounts:update_password' %}" class="list-group-item">Alterar Senha</a>
                  <a href="{% url 'checkout:order_list' %}" class="list-group-item">Meus pedidos</a>
                </div>
            </div>
            <div class="col-md-8">
            {% block accounts_container %}
                <h2>Bem vindo {{user}}</h2>
            {% endblock %}
            </div>
        </div>
{% endblock container %}

accounts/templates/accounts/registration.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block title %}
    Cadastro | {{ block.super }}
{% endblock title %}

{% block container %}
<div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="page-header">
                    <h1>Cadastro</h1>
                </div>
                <form class="form-horizontal" method="post">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error }}
                  </div>
                {% endfor %}
                    <fieldset>
                        <div class="form-group {% if form.errors %} has-error {% endif %}">
                          <label for="{{ form.username.auto_id}}" class="col-md-3 control-label">{{form.username.label}}</label>
                          <div class="col-md-9">
                              {% render_field form.username class="form-control" %}
                              {% for error in form.username.errors %}
                                <span class="help-block">{{ error }}</span>
                              {% endfor %}
                          </div>
                        </div>
                          <div class="form-group {% if form.errors %} has-error {% endif %}">
                          <label for="{{ form.email.auto_id}}" class="col-md-3 control-label">{{form.email.label}}</label>
                          <div class="col-md-9">
                              {% render_field form.email class="form-control" %}
                              {% for error in form.email.errors %}
                                <span class="help-block">{{ error }}</span>
                              {% endfor %}
                          </div>
                        </div>
                        <div class="form-group">
                          <label for="{{ form.password1.auto_id }}" class="col-md-3 control-label">{{form.password1.label}}</label>
                          <div class="col-md-9">
                            {% render_field form.password1 class="form-control" %}
                              {% for error in form.password1.errors %}
                                <span class="help-block">{{ error }}</span>
                              {% endfor %}
                          </div>
                        </div>                        
                        <div class="form-group">
                          <label for="{{ form.password2.auto_id }}" class="col-md-3 control-label">{{form.password2.label}}</label>
                          <div class="col-md-9">
                            {% render_field form.password2 class="form-control" %}
                              {% for error in form.password2.errors %}
                                <span class="help-block">{{ error }}</span>
                              {% endfor %}
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Cadastrar</button>
                            <a href="{% url 'login' %}" type="submit" class="btn btn-success">Login</a>
                          </div>
                        </div>
                    </fieldset>
                </form>
            </div>
  </div>
</div>
{% endblock container %}

accounts/templates/accounts/update_password.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}
{% block title %}
    Alterar Senha | {{ block.super }}
{% endblock title %}
{% block accounts_container %}
	<h2>Alterar dados</h2>
                <form class="form-horizontal" method="post">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error }}
                  </div>
                {% endfor %}
                    <fieldset>
	 <div class="form-group {% if form.errors %} has-error {% endif %}">
		<label for="{{ form.old_password.auto_id}}" class="col-md-3 control-label">{{form.old_password.label}}</label>
        <div class="col-md-9">
        	{% render_field form.old_password class="form-control" %}
            {% for error in form.old_password.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
    	</div>
	</div>
	 <div class="form-group {% if form.errors %} has-error {% endif %}">
		<label for="{{ form.new_password1.auto_id}}" class="col-md-3 control-label">{{form.new_password1.label}}</label>
		<div class="col-md-9">
		{% render_field form.new_password1 class="form-control" %}
		{% for error in form.new_password1.errors %}
			<span class="help-block">{{ error }}</span>
		{% endfor %}
      </div>
    </div>	 <div class="form-group {% if form.errors %} has-error {% endif %}">
		<label for="{{ form.new_password2.auto_id}}" class="col-md-3 control-label">{{form.new_password2.label}}</label>
		<div class="col-md-9">
		{% render_field form.new_password2 class="form-control" %}
		{% for error in form.new_password2.errors %}
			<span class="help-block">{{ error }}</span>
		{% endfor %}
      </div>
    </div>
	<div class="form-group">
	<div class="col-md-9 col-md-offset-3">
	<button type="submit" class="btn btn-primary">Modificar</button>
	</div>
	</div>
{% endblock %}

accounts/templates/accounts/update_user.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}
{% block title %}
    Alterar Dados | {{ block.super }}
{% endblock title %}
{% block accounts_container %}
	<h2>Alterar dados</h2>
                <form class="form-horizontal" method="post">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error }}
                  </div>
                {% endfor %}
                    <fieldset>
	 <div class="form-group {% if form.errors %} has-error {% endif %}">
		<label for="{{ form.name.auto_id}}" class="col-md-3 control-label">{{form.name.label}}</label>
        <div class="col-md-9">
        	{% render_field form.name class="form-control" %}
            {% for error in form.name.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
    	</div>
	</div>
	 <div class="form-group {% if form.errors %} has-error {% endif %}">
		<label for="{{ form.email.auto_id}}" class="col-md-3 control-label">{{form.email.label}}</label>
		<div class="col-md-9">
		{% render_field form.email class="form-control" %}
		{% for error in form.email.errors %}
			<span class="help-block">{{ error }}</span>
		{% endfor %}
      </div>
    </div>
	<div class="form-group">
	<div class="col-md-9 col-md-offset-3">
	<button type="submit" class="btn btn-primary">Modificar</button>
	</div>
	</div>
{% endblock %}